version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqlsecret
      MYSQL_DATABASE: projet_master
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'

  adminer:
    image: adminer
    ports: 
      - '8090:8080'  

    environment:
      ADMINER_DB: projet_master
      ADMINER_PASSWORD: symfony
      ADMINER_SERVER: database
      ADMINER_USERNAME: symfony
      ADMINER_AUTOLOGIN: 0
      ADMINER_NAME: projet_master

    volumes:

      - ./docker/adminer/index.php:/var/www/html/index.php

  php:
      container_name: php
      build:
        dockerfile: docker/php/Dockerfile
        context: .
      ports:
        - '9000:9000'
      volumes:
        - ./symfony/:/var/www/symfony
      depends_on:
        - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database