<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxyZ0bH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxyZ0bH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxyZ0bH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxyZ0bH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXxyZ0bH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XxyZ0bH',
    'container.build_id' => '543b177f',
    'container.build_time' => 1656403604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxyZ0bH');
